/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicRouteImport } from './routes/(public)/route'
import { Route as protectedRouteImport } from './routes/(protected)/route'
import { Route as IndexImport } from './routes/index'
import { Route as protectedSettingsImport } from './routes/(protected)/settings'
import { Route as protectedGalleryIndexImport } from './routes/(protected)/gallery/index'
import { Route as publicInviteTokenImport } from './routes/(public)/invite.$token'
import { Route as publicauthSignupSuccessImport } from './routes/(public)/(auth)/signup-success'
import { Route as publicauthSignUpImport } from './routes/(public)/(auth)/sign-up'
import { Route as publicauthSignInImport } from './routes/(public)/(auth)/sign-in'
import { Route as protectedGalleryFolderIdImport } from './routes/(protected)/gallery/$folderId'

// Create/Update Routes

const publicRouteRoute = publicRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const protectedRouteRoute = protectedRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const protectedSettingsRoute = protectedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)

const protectedGalleryIndexRoute = protectedGalleryIndexImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => protectedRouteRoute,
} as any)

const publicInviteTokenRoute = publicInviteTokenImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => publicRouteRoute,
} as any)

const publicauthSignupSuccessRoute = publicauthSignupSuccessImport.update({
  id: '/(auth)/signup-success',
  path: '/signup-success',
  getParentRoute: () => publicRouteRoute,
} as any)

const publicauthSignUpRoute = publicauthSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)

const publicauthSignInRoute = publicauthSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)

const protectedGalleryFolderIdRoute = protectedGalleryFolderIdImport.update({
  id: '/gallery/$folderId',
  path: '/gallery/$folderId',
  getParentRoute: () => protectedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsImport
      parentRoute: typeof protectedRouteImport
    }
    '/(protected)/gallery/$folderId': {
      id: '/(protected)/gallery/$folderId'
      path: '/gallery/$folderId'
      fullPath: '/gallery/$folderId'
      preLoaderRoute: typeof protectedGalleryFolderIdImport
      parentRoute: typeof protectedRouteImport
    }
    '/(public)/(auth)/sign-in': {
      id: '/(public)/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicauthSignInImport
      parentRoute: typeof publicRouteImport
    }
    '/(public)/(auth)/sign-up': {
      id: '/(public)/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicauthSignUpImport
      parentRoute: typeof publicRouteImport
    }
    '/(public)/(auth)/signup-success': {
      id: '/(public)/(auth)/signup-success'
      path: '/signup-success'
      fullPath: '/signup-success'
      preLoaderRoute: typeof publicauthSignupSuccessImport
      parentRoute: typeof publicRouteImport
    }
    '/(public)/invite/$token': {
      id: '/(public)/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof publicInviteTokenImport
      parentRoute: typeof publicRouteImport
    }
    '/(protected)/gallery/': {
      id: '/(protected)/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof protectedGalleryIndexImport
      parentRoute: typeof protectedRouteImport
    }
  }
}

// Create and export the route tree

interface protectedRouteRouteChildren {
  protectedSettingsRoute: typeof protectedSettingsRoute
  protectedGalleryFolderIdRoute: typeof protectedGalleryFolderIdRoute
  protectedGalleryIndexRoute: typeof protectedGalleryIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSettingsRoute: protectedSettingsRoute,
  protectedGalleryFolderIdRoute: protectedGalleryFolderIdRoute,
  protectedGalleryIndexRoute: protectedGalleryIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicauthSignInRoute: typeof publicauthSignInRoute
  publicauthSignUpRoute: typeof publicauthSignUpRoute
  publicauthSignupSuccessRoute: typeof publicauthSignupSuccessRoute
  publicInviteTokenRoute: typeof publicInviteTokenRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicauthSignInRoute: publicauthSignInRoute,
  publicauthSignUpRoute: publicauthSignUpRoute,
  publicauthSignupSuccessRoute: publicauthSignupSuccessRoute,
  publicInviteTokenRoute: publicInviteTokenRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof publicRouteRouteWithChildren
  '/settings': typeof protectedSettingsRoute
  '/gallery/$folderId': typeof protectedGalleryFolderIdRoute
  '/sign-in': typeof publicauthSignInRoute
  '/sign-up': typeof publicauthSignUpRoute
  '/signup-success': typeof publicauthSignupSuccessRoute
  '/invite/$token': typeof publicInviteTokenRoute
  '/gallery': typeof protectedGalleryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof publicRouteRouteWithChildren
  '/settings': typeof protectedSettingsRoute
  '/gallery/$folderId': typeof protectedGalleryFolderIdRoute
  '/sign-in': typeof publicauthSignInRoute
  '/sign-up': typeof publicauthSignUpRoute
  '/signup-success': typeof publicauthSignupSuccessRoute
  '/invite/$token': typeof publicInviteTokenRoute
  '/gallery': typeof protectedGalleryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(protected)/settings': typeof protectedSettingsRoute
  '/(protected)/gallery/$folderId': typeof protectedGalleryFolderIdRoute
  '/(public)/(auth)/sign-in': typeof publicauthSignInRoute
  '/(public)/(auth)/sign-up': typeof publicauthSignUpRoute
  '/(public)/(auth)/signup-success': typeof publicauthSignupSuccessRoute
  '/(public)/invite/$token': typeof publicInviteTokenRoute
  '/(protected)/gallery/': typeof protectedGalleryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/gallery/$folderId'
    | '/sign-in'
    | '/sign-up'
    | '/signup-success'
    | '/invite/$token'
    | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/gallery/$folderId'
    | '/sign-in'
    | '/sign-up'
    | '/signup-success'
    | '/invite/$token'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(public)'
    | '/(protected)/settings'
    | '/(protected)/gallery/$folderId'
    | '/(public)/(auth)/sign-in'
    | '/(public)/(auth)/sign-up'
    | '/(public)/(auth)/signup-success'
    | '/(public)/invite/$token'
    | '/(protected)/gallery/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(protected)",
        "/(public)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(protected)": {
      "filePath": "(protected)/route.tsx",
      "children": [
        "/(protected)/settings",
        "/(protected)/gallery/$folderId",
        "/(protected)/gallery/"
      ]
    },
    "/(public)": {
      "filePath": "(public)/route.tsx",
      "children": [
        "/(public)/(auth)/sign-in",
        "/(public)/(auth)/sign-up",
        "/(public)/(auth)/signup-success",
        "/(public)/invite/$token"
      ]
    },
    "/(protected)/settings": {
      "filePath": "(protected)/settings.tsx",
      "parent": "/(protected)"
    },
    "/(protected)/gallery/$folderId": {
      "filePath": "(protected)/gallery/$folderId.tsx",
      "parent": "/(protected)"
    },
    "/(public)/(auth)/sign-in": {
      "filePath": "(public)/(auth)/sign-in.tsx",
      "parent": "/(public)"
    },
    "/(public)/(auth)/sign-up": {
      "filePath": "(public)/(auth)/sign-up.tsx",
      "parent": "/(public)"
    },
    "/(public)/(auth)/signup-success": {
      "filePath": "(public)/(auth)/signup-success.tsx",
      "parent": "/(public)"
    },
    "/(public)/invite/$token": {
      "filePath": "(public)/invite.$token.tsx",
      "parent": "/(public)"
    },
    "/(protected)/gallery/": {
      "filePath": "(protected)/gallery/index.tsx",
      "parent": "/(protected)"
    }
  }
}
ROUTE_MANIFEST_END */
